### ISSUE TITLE
Support `tmLanguage` PLIST syntax definition format

### ISSUE THREAD

**Issue by cschmatzler** [msaraiva/vscode-surface#5]
Hi!

I've been trying to make the `.sface` syntax highlighting work in Sublime Text and can't seem to be able to convert it into a format that Sublime is happy with
My steps are:
1. Take `surface.json` and open it in Visual Studio Code
2. Install the [TextMate Languages](https://marketplace.visualstudio.com/items?itemName=Togusa09.tmlanguage) extension
3. Run the `Convert to tmLanguage` command from the command palette
4. Open the resulting `surface.tmLanguage` file in Sublime Text
5. Run the Tools -> Developer -> New Syntax from surface.tmLanguage menu item

This results in
```
pop pattern contains \G, this will not work as expected if it's intended to refer to the begin regex: (?!\G)([ \t]*$\n?)?
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python38/sublime_plugin.py", line 1482, in run_
    return self.run()
  File "/opt/sublime_text/Packages/Default.sublime-package/convert_syntax.py", line 433, in run
  File "/opt/sublime_text/Packages/Default.sublime-package/convert_syntax.py", line 358, in convert
  File "/opt/sublime_text/Packages/Default.sublime-package/convert_syntax.py", line 242, in make_context
KeyError: 'end'
```

Also tried to run this ruby library: https://github.com/aziz/SublimeSyntaxConvertor with the following result:
```
WARNING:
        pop pattern contains \G, this will not work as expected
        if it's intended to refer to the begin regex: (?!\G)([ \t]*$\n?)?
/home/cschmatzler/.local/share/gem/ruby/gems/sublime_syntax_convertor-0.1.0/lib/sublime_syntax_convertor/formatter.rb:10:in `format_regex': undefined method `include?' for nil:NilClass (NoMethodError)
```

Running `Sublime Text Build 4113`.

To be completely honest, I have *very* little knowledge about syntax definitions so I might just be missing something obvious here.
Overall, I think it would be great for adoption to also provide a definition for all the editors that just take `tmLanguage` PLIST definition files. Since I am not sure how much work it would be to provide that, I might be asking too much and this might be an enhancement much further down the road.

Appreciate your time

**Comment by msaraiva** [comment]
Hi @cschmatzler!

It seems those packages haven't been maintained for some time so they probably just have incomplete support for grammars defined in JSON files. Have you tried any of the more recent forks, like [this one](https://github.com/pedro-w/vscode-tmlanguage)?

It states in the README:

> ### Note about this fork (pedro-w)
> 
> The original fork (Togusa9) has not seen any activity since 2018 and unfortunately has a bug which causes it to highlight spurious errors in JSON files which are nothing to do with tmlanguage. I have been unable to get a response from the author via github.com. This fork contains a fix for that bug and some maintenance work covering the changes in vscode from 2018 to now. It also contains some bug fixes from user disco0. I hope to provide a standalong VSIX for download and, if there is interest, I can look into making it available on the extension marketplace. The best outcome would be that the original fork becomes active once again and, if that >happens, I would be delighted to see these changes merged back if required.

Not sure if it might get you anywhere but maybe it worth a try. 

As far as I could see, there's nothing we can do at the grammar level.

**Comment by cschmatzler** [comment]
Hey!

Thanks for finding that for me - unfortunately it doesn't work either. Asked in the Sublime discord and apparently Sublime runs on an older version of the TextMate syntax that doesn't support some of the grammar. Real bummer that there's no cross compatibility.

That being said, I will probably spend some of my time looking into translating it manually and see what I get going there. Time to learn about syntax definitions, I guess. Might be a long while and no promise of success, but let me know if you want me to create a PR on the Surface repo to add it under the Tooling section in the readme in case I succeed.

Cheers, have a wonderful rest of your week!

**Comment by msaraiva** [comment]
> Sublime runs on an older version of the TextMate syntax that doesn't support some of the grammar. Real bummer that there's no cross compatibility.

Real bummer indeed.

> let me know if you want me to create a PR on the Surface repo to add it under the Tooling section in the readme in case I succeed.

Sure! Feel free to open a PR if you succeed.
